



select
    id,
    src_sys_id,
    src_created_at::timestamp as src_created_at,
    src_updated_at::timestamp as src_updated_at,
    display_name,
    name_first,
    name_last,
    name_full,
    mobile_phone_ctc_display_name,
    mobile_phone_ctc_display_number,
    mobile_phone,
    email_email,
    email_as_string,
    office_phone_number,
    office_phone_full,
    home_phone_number,
    home_phone_full,
    home_phone_area,
    address_longitude,
    address_latitude,
    address_street,
    address_street2,
    address_city,
    address_state,
    address_zip,
    address_full,
    email_label,
    description_general_note,
    date_created_date,
    zendesk_id,
    zendesk_link_sml,
    zendesk_link_lrg,
    temp,
    lifetime_value,
    active_job,
    open_opp,
    unpaid_invoice,
    myob_customer_id,
    myob_customer_class,
    created_by,
    no_email,
    no_phone,
    dlt_load_id,
    dlt_id,
    created_at::timestamp as ln_created_at,
    updated_at::timestamp as ln_updated_at
from "dw_dev"."landing_tracker"."ln_contact"
