



select
    id,
    src_sys_id,
    src_created_at::timestamp as src_created_at,
    src_updated_at::timestamp as src_updated_at,
    account_company_name,
    account_type,
    date_created_date,
    lifetime_value,
    child_accounts_lifetime_value,
    group_lifetime_value,
    created_by,
    count_child_account,
    active_job,
    open_opp,
    unpaid_invoice,
    standard_commission,
    abn,
    myob_customer_id,
    myob_customer_class,
    acn,
    cover,
    cover_last_updated_date,
    volume_builder_id_portal,
    cid_qbe,
    cover_expiry_date,
    head_office_address_longitude,
    head_office_address_latitude,
    head_office_address_street,
    head_office_address_street2,
    head_office_address_city,
    head_office_address_state,
    head_office_address_zip,
    head_office_address_full,
    primary_phone,
    description_general_note,
    dlt_load_id,
    dlt_id,
    created_at::timestamp as ln_created_at,
    updated_at::timestamp as ln_updated_at
from "dw_dev"."landing_tracker"."ln_account"
